# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c719075d02dc4c9e59bc3bb8db23c880dc2447f3c2d4f38917b435e9bb0b61b4bdca2e37c97c8eb321922ddfd3be6c6866f7403434be2c9b9db878db3efb742

test:
  secret_key_base: 640d98bea45020865f1086e0229f474d21abbed966c744ec7a103493430b43dc1af1ac7630f7e4c632468dabc640aca0296b75934e85f10f8bec1112c9acf933

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["JMAPWEB_SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["JMAPWEB_SECRET_KEY_BASE"] %>
